package com.ringoid.view;
/*Copyright (c) Ringoid Ltd, 2018. All Rights Reserved*/

enum PAGE_ENUM {
    LOGIN,
    PROFILE_UPDATE,
    FEED,
    CHAT,
    PHOTO_CROP,
    PHOTO_ADD,
    BLACKLIST_PHONES,
    BLACKLIST_PHONES_ADD,
    FEEDBACK,
    EMAIL_OFFICER,
    WEBVIEW,
    WEBVIEW_EXTERNAL,
    SETTINGS,
    SETTINGS_DATA_PROTECTION,
    SETTINGS_DEBUG,
    SETTINGS_PRIVACY_DISTANCE,
    FEED_LIKES, FEED_PROFILE, FEED_MESSAGES, FEED_EXPLORE, SETTINGS_PUSH

}
