package com.ringoid.view;
/*Copyright (c) Ringoid Ltd, 2018. All Rights Reserved*/

public enum PAGE_ENUM {
    UNKNOWN,
    FEED,
    CHAT,
    FEED_PROFILE,
    FEED_LIKES,
    FEED_MESSAGES,
    FEED_EXPLORE
    /*SETTINGS_PUSH
    PHOTO_CROP,
    PHOTO_ADD,
    BLACKLIST_PHONES,
    BLACKLIST_PHONES_ADD,
    FEEDBACK,
    EMAIL_OFFICER,
    WEBVIEW,
    WEBVIEW_EXTERNAL,
    SETTINGS,
    SETTINGS_DATA_PROTECTION,
    SETTINGS_DEBUG,
    SETTINGS_PRIVACY_DISTANCE,
    LOGIN,
    PROFILE_UPDATE,*/
}
